// Build-time stubs for vendored grammars excluded from the released 12-language build.
// The upstream language registry references every grammar; returning NULL keeps those
// optional entries unavailable without compiling their parser/scanner units.
#include <stddef.h>
#include "tree_sitter/api.h"

const TSLanguage *tree_sitter_tsx(void) { return NULL; }
const TSLanguage *tree_sitter_lua(void) { return NULL; }
const TSLanguage *tree_sitter_scala(void) { return NULL; }
const TSLanguage *tree_sitter_kotlin(void) { return NULL; }
const TSLanguage *tree_sitter_bash(void) { return NULL; }
const TSLanguage *tree_sitter_zig(void) { return NULL; }
const TSLanguage *tree_sitter_elixir(void) { return NULL; }
const TSLanguage *tree_sitter_haskell(void) { return NULL; }
const TSLanguage *tree_sitter_ocaml(void) { return NULL; }
const TSLanguage *tree_sitter_objc(void) { return NULL; }
const TSLanguage *tree_sitter_swift(void) { return NULL; }
const TSLanguage *tree_sitter_perl(void) { return NULL; }
const TSLanguage *tree_sitter_groovy(void) { return NULL; }
const TSLanguage *tree_sitter_erlang(void) { return NULL; }
const TSLanguage *tree_sitter_r(void) { return NULL; }
const TSLanguage *tree_sitter_html(void) { return NULL; }
const TSLanguage *tree_sitter_css(void) { return NULL; }
const TSLanguage *tree_sitter_scss(void) { return NULL; }
const TSLanguage *tree_sitter_yaml(void) { return NULL; }
const TSLanguage *tree_sitter_toml(void) { return NULL; }
const TSLanguage *tree_sitter_hcl(void) { return NULL; }
const TSLanguage *tree_sitter_sql(void) { return NULL; }
const TSLanguage *tree_sitter_dockerfile(void) { return NULL; }
const TSLanguage *tree_sitter_clojure(void) { return NULL; }
const TSLanguage *tree_sitter_fsharp(void) { return NULL; }
const TSLanguage *tree_sitter_julia(void) { return NULL; }
const TSLanguage *tree_sitter_vim(void) { return NULL; }
const TSLanguage *tree_sitter_nix(void) { return NULL; }
const TSLanguage *tree_sitter_commonlisp(void) { return NULL; }
const TSLanguage *tree_sitter_elm(void) { return NULL; }
const TSLanguage *tree_sitter_fortran(void) { return NULL; }
const TSLanguage *tree_sitter_cuda(void) { return NULL; }
const TSLanguage *tree_sitter_COBOL(void) { return NULL; }
const TSLanguage *tree_sitter_verilog(void) { return NULL; }
const TSLanguage *tree_sitter_elisp(void) { return NULL; }
const TSLanguage *tree_sitter_json(void) { return NULL; }
const TSLanguage *tree_sitter_xml(void) { return NULL; }
const TSLanguage *tree_sitter_markdown(void) { return NULL; }
const TSLanguage *tree_sitter_make(void) { return NULL; }
const TSLanguage *tree_sitter_cmake(void) { return NULL; }
const TSLanguage *tree_sitter_proto(void) { return NULL; }
const TSLanguage *tree_sitter_graphql(void) { return NULL; }
const TSLanguage *tree_sitter_vue(void) { return NULL; }
const TSLanguage *tree_sitter_svelte(void) { return NULL; }
const TSLanguage *tree_sitter_meson(void) { return NULL; }
const TSLanguage *tree_sitter_glsl(void) { return NULL; }
const TSLanguage *tree_sitter_ini(void) { return NULL; }
const TSLanguage *tree_sitter_matlab(void) { return NULL; }
const TSLanguage *tree_sitter_lean(void) { return NULL; }
const TSLanguage *tree_sitter_form(void) { return NULL; }
const TSLanguage *tree_sitter_magma(void) { return NULL; }
const TSLanguage *tree_sitter_wolfram(void) { return NULL; }
const TSLanguage *tree_sitter_solidity(void) { return NULL; }
const TSLanguage *tree_sitter_typst(void) { return NULL; }
const TSLanguage *tree_sitter_gdscript(void) { return NULL; }
const TSLanguage *tree_sitter_gleam(void) { return NULL; }
const TSLanguage *tree_sitter_powershell(void) { return NULL; }
const TSLanguage *tree_sitter_pascal(void) { return NULL; }
const TSLanguage *tree_sitter_d(void) { return NULL; }
const TSLanguage *tree_sitter_scheme(void) { return NULL; }
const TSLanguage *tree_sitter_fennel(void) { return NULL; }
const TSLanguage *tree_sitter_fish(void) { return NULL; }
const TSLanguage *tree_sitter_awk(void) { return NULL; }
const TSLanguage *tree_sitter_zsh(void) { return NULL; }
const TSLanguage *tree_sitter_tcl(void) { return NULL; }
const TSLanguage *tree_sitter_ada(void) { return NULL; }
const TSLanguage *tree_sitter_agda(void) { return NULL; }
const TSLanguage *tree_sitter_racket(void) { return NULL; }
const TSLanguage *tree_sitter_odin(void) { return NULL; }
const TSLanguage *tree_sitter_rescript(void) { return NULL; }
const TSLanguage *tree_sitter_purescript(void) { return NULL; }
const TSLanguage *tree_sitter_nickel(void) { return NULL; }
const TSLanguage *tree_sitter_crystal(void) { return NULL; }
const TSLanguage *tree_sitter_teal(void) { return NULL; }
const TSLanguage *tree_sitter_hare(void) { return NULL; }
const TSLanguage *tree_sitter_pony(void) { return NULL; }
const TSLanguage *tree_sitter_luau(void) { return NULL; }
const TSLanguage *tree_sitter_qmljs(void) { return NULL; }
const TSLanguage *tree_sitter_cfscript(void) { return NULL; }
const TSLanguage *tree_sitter_cfml(void) { return NULL; }
const TSLanguage *tree_sitter_janet_simple(void) { return NULL; }
const TSLanguage *tree_sitter_sway(void) { return NULL; }
const TSLanguage *tree_sitter_nasm(void) { return NULL; }
const TSLanguage *tree_sitter_asm(void) { return NULL; }
const TSLanguage *tree_sitter_astro(void) { return NULL; }
const TSLanguage *tree_sitter_blade(void) { return NULL; }
const TSLanguage *tree_sitter_just(void) { return NULL; }
const TSLanguage *tree_sitter_gotmpl(void) { return NULL; }
const TSLanguage *tree_sitter_templ(void) { return NULL; }
const TSLanguage *tree_sitter_liquid(void) { return NULL; }
const TSLanguage *tree_sitter_jinja2(void) { return NULL; }
const TSLanguage *tree_sitter_prisma(void) { return NULL; }
const TSLanguage *tree_sitter_hyprlang(void) { return NULL; }
const TSLanguage *tree_sitter_dotenv(void) { return NULL; }
const TSLanguage *tree_sitter_diff(void) { return NULL; }
const TSLanguage *tree_sitter_wgsl(void) { return NULL; }
const TSLanguage *tree_sitter_kdl(void) { return NULL; }
const TSLanguage *tree_sitter_json5(void) { return NULL; }
const TSLanguage *tree_sitter_jsonnet(void) { return NULL; }
const TSLanguage *tree_sitter_ron(void) { return NULL; }
const TSLanguage *tree_sitter_thrift(void) { return NULL; }
const TSLanguage *tree_sitter_capnp(void) { return NULL; }
const TSLanguage *tree_sitter_properties(void) { return NULL; }
const TSLanguage *tree_sitter_ssh_config(void) { return NULL; }
const TSLanguage *tree_sitter_bibtex(void) { return NULL; }
const TSLanguage *tree_sitter_starlark(void) { return NULL; }
const TSLanguage *tree_sitter_bicep(void) { return NULL; }
const TSLanguage *tree_sitter_csv(void) { return NULL; }
const TSLanguage *tree_sitter_requirements(void) { return NULL; }
const TSLanguage *tree_sitter_hlsl(void) { return NULL; }
const TSLanguage *tree_sitter_vhdl(void) { return NULL; }
const TSLanguage *tree_sitter_systemverilog(void) { return NULL; }
const TSLanguage *tree_sitter_devicetree(void) { return NULL; }
const TSLanguage *tree_sitter_linkerscript(void) { return NULL; }
const TSLanguage *tree_sitter_gn(void) { return NULL; }
const TSLanguage *tree_sitter_kconfig(void) { return NULL; }
const TSLanguage *tree_sitter_bitbake(void) { return NULL; }
const TSLanguage *tree_sitter_smali(void) { return NULL; }
const TSLanguage *tree_sitter_tablegen(void) { return NULL; }
const TSLanguage *tree_sitter_ispc(void) { return NULL; }
const TSLanguage *tree_sitter_cairo(void) { return NULL; }
const TSLanguage *tree_sitter_move(void) { return NULL; }
const TSLanguage *tree_sitter_squirrel(void) { return NULL; }
const TSLanguage *tree_sitter_func(void) { return NULL; }
const TSLanguage *tree_sitter_regex(void) { return NULL; }
const TSLanguage *tree_sitter_jsdoc(void) { return NULL; }
const TSLanguage *tree_sitter_rst(void) { return NULL; }
const TSLanguage *tree_sitter_beancount(void) { return NULL; }
const TSLanguage *tree_sitter_mermaid(void) { return NULL; }
const TSLanguage *tree_sitter_puppet(void) { return NULL; }
const TSLanguage *tree_sitter_po(void) { return NULL; }
const TSLanguage *tree_sitter_gitattributes(void) { return NULL; }
const TSLanguage *tree_sitter_gitignore(void) { return NULL; }
const TSLanguage *tree_sitter_slang(void) { return NULL; }
const TSLanguage *tree_sitter_llvm(void) { return NULL; }
const TSLanguage *tree_sitter_smithy(void) { return NULL; }
const TSLanguage *tree_sitter_wit(void) { return NULL; }
const TSLanguage *tree_sitter_tlaplus(void) { return NULL; }
const TSLanguage *tree_sitter_pkl(void) { return NULL; }
const TSLanguage *tree_sitter_gomod(void) { return NULL; }
const TSLanguage *tree_sitter_apex(void) { return NULL; }
const TSLanguage *tree_sitter_soql(void) { return NULL; }
const TSLanguage *tree_sitter_sosl(void) { return NULL; }
const TSLanguage *tree_sitter_pine(void) { return NULL; }
